server:
  port: 8082

spring:
  application:
    name: taskmanager
  profiles:
    active: dev

  #Postgresql DB Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskManagerDb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres@2026

  #H2 console configuration
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  #JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# App info
app:
  name: Task Manager
  version: 1.0.0
  max-tasks-per-page: 10

#actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,logger,beans,mappings
      base-path: /actuator

  endppoints:
    health:
      show-details: always

    info:
      env:
        enabled: true

info:
  app:
    description: A simple task management application built with Spring boot.
    version: 1.0.0
    author: Kenny Kay
